# Generated by Django 5.2.1 on 2025-05-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(to='data.genre'),
        ),
    ]
